### ISSUE TITLE
Unknown option: base.stage

### ISSUE THREAD

**Issue by stereodenis** [alexfedoseev/generator-flux-on-rails#5]
after first gulp

```
my-blog-app rbenv:(2.2.3) git:(master) ✗ gulp                          
[00:42:35] Requiring external module babel-core/register
/Users/stereodenis/work/test/my-blog/my-blog-app/node_modules/babel-core/lib/transformation/file/logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /Users/stereodenis/work/test/my-blog/my-blog-app/gulpfile.babel.js: Unknown option: base.stage
    at Logger.error (/Users/stereodenis/work/test/my-blog/my-blog-app/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/stereodenis/work/test/my-blog/my-blog-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.init (/Users/stereodenis/work/test/my-blog/my-blog-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
    at File.initOptions (/Users/stereodenis/work/test/my-blog/my-blog-app/node_modules/babel-core/lib/transformation/file/index.js:190:75)
    at new File (/Users/stereodenis/work/test/my-blog/my-blog-app/node_modules/babel-core/lib/transformation/file/index.js:121:22)
    at Pipeline.transform (/Users/stereodenis/work/test/my-blog/my-blog-app/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Object.transformFileSync (/Users/stereodenis/work/test/my-blog/my-blog-app/node_modules/babel-core/lib/api/node.js:116:10)
    at compile (/Users/stereodenis/work/test/my-blog/my-blog-app/node_modules/babel-register/lib/node.js:102:20)
    at loader (/Users/stereodenis/work/test/my-blog/my-blog-app/node_modules/babel-register/lib/node.js:130:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/stereodenis/work/test/my-blog/my-blog-app/node_modules/babel-register/lib/node.js:140:7)
```

**Comment by alex35mil** [comment]
@stereodenis Same here, it's broken b/c of updated npm packages. I'll push updated version of this generator as PR soon.

**Comment by stereodenis** [comment]
@alexfedoseev thanks! Want to try this bundle

**Comment by kofronpi** [comment]
@alexfedoseev I'm fine with the backend part, will I be able to just regenerate the node app ? thanks for your work !

**Comment by alex35mil** [comment]
@kofronpi I don't think so, a lot of modules (e.g. React, Redux, Babel etc.) were bumped to next major versions, so their API were changed. You need to provide old versions of all updated modules explicitly (not recommended) or update generated sources to new APIs (this is what I did in my current local branch + added new stuff e.g. Isomorphic CSS Modules, Immutable.js, normalizr etc.). I'll push my current work (even it's not finished) to new branch this weekend and create PR, so you'll be able to check it out. I'll cc you guys there.

**Comment by kofronpi** [comment]
@alexfedoseev that'll be fine, I didn't start working on the node app yet. I'll be able to connect the dots. Thanks !

**Comment by alex35mil** [comment]
@stereodenis @kofronpi I pushed updates, check out details in this PR: https://github.com/alexfedoseev/generator-flux-on-rails/pull/6
