### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by alecguintu** [alexfedoseev/generator-flux-on-rails#8]
Hello! I wanted to try this out but bare with me as this is my first time to try out generator's and npm's. I have small experience with React and Flux with the `react-rails` but I want to make rails as an API as well and start react+flux as universal javascript and this is where I got to. Now when I generated this generator with just the `NodeApp` and did an `npm start` I get this error:

```
-> % npm start

> test-app-app@0.0.1 start /Users/alice/Sites/flux-on-rails/test-app/test-app-app
> gulp start:dev

[11:14:09] Requiring external module babel-register
/Users/alice/Sites/flux-on-rails/test-app/test-app-app/node_modules/babel-core/lib/transformation/file/logger.js:39
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /Users/alice/Sites/flux-on-rails/test-app/test-app-app/gulpfile.babel.js: Using removed Babel 5 option: base.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error (/Users/alice/Sites/flux-on-rails/test-app/test-app-app/node_modules/babel-core/lib/transformation/file/logger.js:39:11)
    at OptionManager.mergeOptions (/Users/alice/Sites/flux-on-rails/test-app/test-app-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:20)
    at OptionManager.init (/Users/alice/Sites/flux-on-rails/test-app/test-app-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
    at File.initOptions (/Users/alice/Sites/flux-on-rails/test-app/test-app-app/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/Users/alice/Sites/flux-on-rails/test-app/test-app-app/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/Users/alice/Sites/flux-on-rails/test-app/test-app-app/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at Object.transformFileSync (/Users/alice/Sites/flux-on-rails/test-app/test-app-app/node_modules/babel-core/lib/api/node.js:124:10)
    at compile (/Users/alice/Sites/flux-on-rails/test-app/test-app-app/node_modules/babel-register/lib/node.js:98:20)
    at loader (/Users/alice/Sites/flux-on-rails/test-app/test-app-app/node_modules/babel-register/lib/node.js:126:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/alice/Sites/flux-on-rails/test-app/test-app-app/node_modules/babel-register/lib/node.js:136:7)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.7.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! test-app-app@0.0.1 start: `gulp start:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-app-app@0.0.1 start script 'gulp start:dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test-app-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp start:dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test-app-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test-app-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alice/Sites/flux-on-rails/test-app/test-app-app/npm-debug.log
```

Have I forgotten other things to install via `npm`? I also attach here the `npm-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.7.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.6.0
3 info using node@v5.7.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle test-app-app@0.0.1~prestart: test-app-app@0.0.1
6 silly lifecycle test-app-app@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle test-app-app@0.0.1~start: test-app-app@0.0.1
8 verbose lifecycle test-app-app@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle test-app-app@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/alice/Sites/flux-on-rails/test-app/test-app-app/node_modules/.bin:/Users/alice/.rvm/gems/ruby-2.2.1@test-app/bin:/Users/alice/.rvm/gems/ruby-2.2.1@global/bin:/Users/alice/.rvm/rubies/ruby-2.2.1/bin:/Users/alice/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle test-app-app@0.0.1~start: CWD: /Users/alice/Sites/flux-on-rails/test-app/test-app-app
11 silly lifecycle test-app-app@0.0.1~start: Args: [ '-c', 'gulp start:dev' ]
12 silly lifecycle test-app-app@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle test-app-app@0.0.1~start: Failed to exec start script
14 verbose stack Error: test-app-app@0.0.1 start: `gulp start:dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid test-app-app@0.0.1
16 verbose cwd /Users/alice/Sites/flux-on-rails/test-app/test-app-app
17 error Darwin 15.0.0
18 error argv "/usr/local/Cellar/node/5.7.1/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.7.1
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error test-app-app@0.0.1 start: `gulp start:dev`
22 error Exit status 1
23 error Failed at the test-app-app@0.0.1 start script 'gulp start:dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the test-app-app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp start:dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs test-app-app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls test-app-app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by alex35mil** [comment]
@alecguintu Most likely you're doing everything right, but currently generator is broken. Check out https://github.com/alexfedoseev/generator-flux-on-rails/pull/6 for more info.
